import React from "react";

interface Prop {
    style?: React.CSSProperties;
    className?: string;
}

const NodeJs: React.FC<Prop> = ({ style, className }) => {
  return (
    <svg
      className={className}
      viewBox="0 0 130 130"
      xmlns="http://www.w3.org/2000/svg"
      style={style}
    >
      <circle cx="58" cy="2" r="2" fill="inherit" />
              <circle cx="62" cy="2" r="2" fill="inherit" />
              <circle cx="66" cy="2" r="2" fill="inherit" />
              <circle cx="54" cy="6" r="2" fill="inherit" />
              <circle cx="58" cy="6" r="2" fill="inherit" />
              <circle cx="62" cy="6" r="2" fill="inherit" />
              <circle cx="66" cy="6" r="2" fill="inherit" />
              <circle cx="70" cy="6" r="2" fill="inherit" />
              <circle cx="74" cy="6" r="2" fill="inherit" />
              <circle cx="46" cy="10" r="2" fill="inherit" />
              <circle cx="50" cy="10" r="2" fill="inherit" />
              <circle cx="54" cy="10" r="2" fill="inherit" />
              <circle cx="58" cy="10" r="2" fill="inherit" />
              <circle cx="70" cy="10" r="2" fill="inherit" />
              <circle cx="74" cy="10" r="2" fill="inherit" />
              <circle cx="78" cy="10" r="2" fill="inherit" />
              <circle cx="82" cy="10" r="2" fill="inherit" />
              <circle cx="38" cy="14" r="2" fill="inherit" />
              <circle cx="42" cy="14" r="2" fill="inherit" />
              <circle cx="46" cy="14" r="2" fill="inherit" />
              <circle cx="50" cy="14" r="2" fill="inherit" />
              <circle cx="78" cy="14" r="2" fill="inherit" />
              <circle cx="82" cy="14" r="2" fill="inherit" />
              <circle cx="86" cy="14" r="2" fill="inherit" />
              <circle cx="90" cy="14" r="2" fill="inherit" />
              <circle cx="30" cy="18" r="2" fill="inherit" />
              <circle cx="34" cy="18" r="2" fill="inherit" />
              <circle cx="38" cy="18" r="2" fill="inherit" />
              <circle cx="42" cy="18" r="2" fill="inherit" />
              <circle cx="86" cy="18" r="2" fill="inherit" />
              <circle cx="90" cy="18" r="2" fill="inherit" />
              <circle cx="94" cy="18" r="2" fill="inherit" />
              <circle cx="26" cy="22" r="2" fill="inherit" />
              <circle cx="30" cy="22" r="2" fill="inherit" />
              <circle cx="34" cy="22" r="2" fill="inherit" />
              <circle cx="90" cy="22" r="2" fill="inherit" />
              <circle cx="94" cy="22" r="2" fill="inherit" />
              <circle cx="98" cy="22" r="2" fill="inherit" />
              <circle cx="102" cy="22" r="2" fill="inherit" />
              <circle cx="18" cy="26" r="2" fill="inherit" />
              <circle cx="22" cy="26" r="2" fill="inherit" />
              <circle cx="26" cy="26" r="2" fill="inherit" />
              <circle cx="30" cy="26" r="2" fill="inherit" />
              <circle cx="98" cy="26" r="2" fill="inherit" />
              <circle cx="102" cy="26" r="2" fill="inherit" />
              <circle cx="106" cy="26" r="2" fill="inherit" />
              <circle cx="110" cy="26" r="2" fill="inherit" />
              <circle cx="10" cy="30" r="2" fill="inherit" />
              <circle cx="14" cy="30" r="2" fill="inherit" />
              <circle cx="18" cy="30" r="2" fill="inherit" />
              <circle cx="22" cy="30" r="2" fill="inherit" />
              <circle cx="106" cy="30" r="2" fill="inherit" />
              <circle cx="110" cy="30" r="2" fill="inherit" />
              <circle cx="114" cy="30" r="2" fill="inherit" />
              <circle cx="10" cy="34" r="2" fill="inherit" />
              <circle cx="14" cy="34" r="2" fill="inherit" />
              <circle cx="110" cy="34" r="2" fill="inherit" />
              <circle cx="114" cy="34" r="2" fill="inherit" />
              <circle cx="118" cy="34" r="2" fill="inherit" />
              <circle cx="10" cy="38" r="2" fill="inherit" />
              <circle cx="14" cy="38" r="2" fill="inherit" />
              <circle cx="114" cy="38" r="2" fill="inherit" />
              <circle cx="118" cy="38" r="2" fill="inherit" />
              <circle cx="10" cy="42" r="2" fill="inherit" />
              <circle cx="14" cy="42" r="2" fill="inherit" />
              <circle cx="42" cy="42" r="2" fill="inherit" />
              <circle cx="46" cy="42" r="2" fill="inherit" />
              <circle cx="62" cy="42" r="2" fill="inherit" />
              <circle cx="66" cy="42" r="2" fill="inherit" />
              <circle cx="70" cy="42" r="2" fill="inherit" />
              <circle cx="74" cy="42" r="2" fill="inherit" />
              <circle cx="78" cy="42" r="2" fill="inherit" />
              <circle cx="82" cy="42" r="2" fill="inherit" />
              <circle cx="86" cy="42" r="2" fill="inherit" />
              <circle cx="90" cy="42" r="2" fill="inherit" />
              <circle cx="114" cy="42" r="2" fill="inherit" />
              <circle cx="118" cy="42" r="2" fill="inherit" />
              <circle cx="10" cy="46" r="2" fill="inherit" />
              <circle cx="14" cy="46" r="2" fill="inherit" />
              <circle cx="42" cy="46" r="2" fill="inherit" />
              <circle cx="46" cy="46" r="2" fill="inherit" />
              <circle cx="58" cy="46" r="2" fill="inherit" />
              <circle cx="62" cy="46" r="2" fill="inherit" />
              <circle cx="66" cy="46" r="2" fill="inherit" />
              <circle cx="70" cy="46" r="2" fill="inherit" />
              <circle cx="74" cy="46" r="2" fill="inherit" />
              <circle cx="78" cy="46" r="2" fill="inherit" />
              <circle cx="82" cy="46" r="2" fill="inherit" />
              <circle cx="86" cy="46" r="2" fill="inherit" />
              <circle cx="90" cy="46" r="2" fill="inherit" />
              <circle cx="94" cy="46" r="2" fill="inherit" />
              <circle cx="114" cy="46" r="2" fill="inherit" />
              <circle cx="118" cy="46" r="2" fill="inherit" />
              <circle cx="10" cy="50" r="2" fill="inherit" />
              <circle cx="14" cy="50" r="2" fill="inherit" />
              <circle cx="42" cy="50" r="2" fill="inherit" />
              <circle cx="46" cy="50" r="2" fill="inherit" />
              <circle cx="58" cy="50" r="2" fill="inherit" />
              <circle cx="62" cy="50" r="2" fill="inherit" />
              <circle cx="90" cy="50" r="2" fill="inherit" />
              <circle cx="94" cy="50" r="2" fill="inherit" />
              <circle cx="98" cy="50" r="2" fill="inherit" />
              <circle cx="114" cy="50" r="2" fill="inherit" />
              <circle cx="118" cy="50" r="2" fill="inherit" />
              <circle cx="10" cy="54" r="2" fill="inherit" />
              <circle cx="14" cy="54" r="2" fill="inherit" />
              <circle cx="42" cy="54" r="2" fill="inherit" />
              <circle cx="46" cy="54" r="2" fill="inherit" />
              <circle cx="58" cy="54" r="2" fill="inherit" />
              <circle cx="62" cy="54" r="2" fill="inherit" />
              <circle cx="94" cy="54" r="2" fill="inherit" />
              <circle cx="98" cy="54" r="2" fill="inherit" />
              <circle cx="114" cy="54" r="2" fill="inherit" />
              <circle cx="118" cy="54" r="2" fill="inherit" />
              <circle cx="10" cy="58" r="2" fill="inherit" />
              <circle cx="14" cy="58" r="2" fill="inherit" />
              <circle cx="42" cy="58" r="2" fill="inherit" />
              <circle cx="46" cy="58" r="2" fill="inherit" />
              <circle cx="58" cy="58" r="2" fill="inherit" />
              <circle cx="62" cy="58" r="2" fill="inherit" />
              <circle cx="66" cy="58" r="2" fill="inherit" />
              <circle cx="114" cy="58" r="2" fill="inherit" />
              <circle cx="118" cy="58" r="2" fill="inherit" />
              <circle cx="10" cy="62" r="2" fill="inherit" />
              <circle cx="14" cy="62" r="2" fill="inherit" />
              <circle cx="42" cy="62" r="2" fill="inherit" />
              <circle cx="46" cy="62" r="2" fill="inherit" />
              <circle cx="62" cy="62" r="2" fill="inherit" />
              <circle cx="66" cy="62" r="2" fill="inherit" />
              <circle cx="70" cy="62" r="2" fill="inherit" />
              <circle cx="74" cy="62" r="2" fill="inherit" />
              <circle cx="78" cy="62" r="2" fill="inherit" />
              <circle cx="82" cy="62" r="2" fill="inherit" />
              <circle cx="86" cy="62" r="2" fill="inherit" />
              <circle cx="90" cy="62" r="2" fill="inherit" />
              <circle cx="114" cy="62" r="2" fill="inherit" />
              <circle cx="118" cy="62" r="2" fill="inherit" />
              <circle cx="10" cy="66" r="2" fill="inherit" />
              <circle cx="14" cy="66" r="2" fill="inherit" />
              <circle cx="42" cy="66" r="2" fill="inherit" />
              <circle cx="46" cy="66" r="2" fill="inherit" />
              <circle cx="70" cy="66" r="2" fill="inherit" />
              <circle cx="74" cy="66" r="2" fill="inherit" />
              <circle cx="78" cy="66" r="2" fill="inherit" />
              <circle cx="82" cy="66" r="2" fill="inherit" />
              <circle cx="86" cy="66" r="2" fill="inherit" />
              <circle cx="90" cy="66" r="2" fill="inherit" />
              <circle cx="94" cy="66" r="2" fill="inherit" />
              <circle cx="98" cy="66" r="2" fill="inherit" />
              <circle cx="114" cy="66" r="2" fill="inherit" />
              <circle cx="118" cy="66" r="2" fill="inherit" />
              <circle cx="10" cy="70" r="2" fill="inherit" />
              <circle cx="14" cy="70" r="2" fill="inherit" />
              <circle cx="42" cy="70" r="2" fill="inherit" />
              <circle cx="46" cy="70" r="2" fill="inherit" />
              <circle cx="90" cy="70" r="2" fill="inherit" />
              <circle cx="94" cy="70" r="2" fill="inherit" />
              <circle cx="98" cy="70" r="2" fill="inherit" />
              <circle cx="114" cy="70" r="2" fill="inherit" />
              <circle cx="118" cy="70" r="2" fill="inherit" />
              <circle cx="10" cy="74" r="2" fill="inherit" />
              <circle cx="14" cy="74" r="2" fill="inherit" />
              <circle cx="42" cy="74" r="2" fill="inherit" />
              <circle cx="46" cy="74" r="2" fill="inherit" />
              <circle cx="54" cy="74" r="2" fill="inherit" />
              <circle cx="58" cy="74" r="2" fill="inherit" />
              <circle cx="94" cy="74" r="2" fill="inherit" />
              <circle cx="98" cy="74" r="2" fill="inherit" />
              <circle cx="114" cy="74" r="2" fill="inherit" />
              <circle cx="118" cy="74" r="2" fill="inherit" />
              <circle cx="10" cy="78" r="2" fill="inherit" />
              <circle cx="14" cy="78" r="2" fill="inherit" />
              <circle cx="42" cy="78" r="2" fill="inherit" />
              <circle cx="46" cy="78" r="2" fill="inherit" />
              <circle cx="58" cy="78" r="2" fill="inherit" />
              <circle cx="62" cy="78" r="2" fill="inherit" />
              <circle cx="94" cy="78" r="2" fill="inherit" />
              <circle cx="98" cy="78" r="2" fill="inherit" />
              <circle cx="114" cy="78" r="2" fill="inherit" />
              <circle cx="118" cy="78" r="2" fill="inherit" />
              <circle cx="10" cy="82" r="2" fill="inherit" />
              <circle cx="14" cy="82" r="2" fill="inherit" />
              <circle cx="42" cy="82" r="2" fill="inherit" />
              <circle cx="46" cy="82" r="2" fill="inherit" />
              <circle cx="58" cy="82" r="2" fill="inherit" />
              <circle cx="62" cy="82" r="2" fill="inherit" />
              <circle cx="66" cy="82" r="2" fill="inherit" />
              <circle cx="70" cy="82" r="2" fill="inherit" />
              <circle cx="86" cy="82" r="2" fill="inherit" />
              <circle cx="90" cy="82" r="2" fill="inherit" />
              <circle cx="94" cy="82" r="2" fill="inherit" />
              <circle cx="98" cy="82" r="2" fill="inherit" />
              <circle cx="114" cy="82" r="2" fill="inherit" />
              <circle cx="118" cy="82" r="2" fill="inherit" />
              <circle cx="10" cy="86" r="2" fill="inherit" />
              <circle cx="14" cy="86" r="2" fill="inherit" />
              <circle cx="42" cy="86" r="2" fill="inherit" />
              <circle cx="46" cy="86" r="2" fill="inherit" />
              <circle cx="62" cy="86" r="2" fill="inherit" />
              <circle cx="66" cy="86" r="2" fill="inherit" />
              <circle cx="70" cy="86" r="2" fill="inherit" />
              <circle cx="74" cy="86" r="2" fill="inherit" />
              <circle cx="78" cy="86" r="2" fill="inherit" />
              <circle cx="82" cy="86" r="2" fill="inherit" />
              <circle cx="86" cy="86" r="2" fill="inherit" />
              <circle cx="90" cy="86" r="2" fill="inherit" />
              <circle cx="94" cy="86" r="2" fill="inherit" />
              <circle cx="114" cy="86" r="2" fill="inherit" />
              <circle cx="118" cy="86" r="2" fill="inherit" />
              <circle cx="10" cy="90" r="2" fill="inherit" />
              <circle cx="14" cy="90" r="2" fill="inherit" />
              <circle cx="42" cy="90" r="2" fill="inherit" />
              <circle cx="46" cy="90" r="2" fill="inherit" />
              <circle cx="114" cy="90" r="2" fill="inherit" />
              <circle cx="118" cy="90" r="2" fill="inherit" />
              <circle cx="10" cy="94" r="2" fill="inherit" />
              <circle cx="14" cy="94" r="2" fill="inherit" />
              <circle cx="18" cy="94" r="2" fill="inherit" />
              <circle cx="42" cy="94" r="2" fill="inherit" />
              <circle cx="46" cy="94" r="2" fill="inherit" />
              <circle cx="110" cy="94" r="2" fill="inherit" />
              <circle cx="114" cy="94" r="2" fill="inherit" />
              <circle cx="118" cy="94" r="2" fill="inherit" />
              <circle cx="14" cy="98" r="2" fill="inherit" />
              <circle cx="18" cy="98" r="2" fill="inherit" />
              <circle cx="22" cy="98" r="2" fill="inherit" />
              <circle cx="42" cy="98" r="2" fill="inherit" />
              <circle cx="46" cy="98" r="2" fill="inherit" />
              <circle cx="102" cy="98" r="2" fill="inherit" />
              <circle cx="106" cy="98" r="2" fill="inherit" />
              <circle cx="110" cy="98" r="2" fill="inherit" />
              <circle cx="114" cy="98" r="2" fill="inherit" />
              <circle cx="18" cy="102" r="2" fill="inherit" />
              <circle cx="22" cy="102" r="2" fill="inherit" />
              <circle cx="26" cy="102" r="2" fill="inherit" />
              <circle cx="30" cy="102" r="2" fill="inherit" />
              <circle cx="34" cy="102" r="2" fill="inherit" />
              <circle cx="38" cy="102" r="2" fill="inherit" />
              <circle cx="42" cy="102" r="2" fill="inherit" />
              <circle cx="46" cy="102" r="2" fill="inherit" />
              <circle cx="98" cy="102" r="2" fill="inherit" />
              <circle cx="102" cy="102" r="2" fill="inherit" />
              <circle cx="106" cy="102" r="2" fill="inherit" />
              <circle cx="26" cy="106" r="2" fill="inherit" />
              <circle cx="30" cy="106" r="2" fill="inherit" />
              <circle cx="34" cy="106" r="2" fill="inherit" />
              <circle cx="38" cy="106" r="2" fill="inherit" />
              <circle cx="42" cy="106" r="2" fill="inherit" />
              <circle cx="90" cy="106" r="2" fill="inherit" />
              <circle cx="94" cy="106" r="2" fill="inherit" />
              <circle cx="98" cy="106" r="2" fill="inherit" />
              <circle cx="102" cy="106" r="2" fill="inherit" />
              <circle cx="82" cy="110" r="2" fill="inherit" />
              <circle cx="86" cy="110" r="2" fill="inherit" />
              <circle cx="90" cy="110" r="2" fill="inherit" />
              <circle cx="94" cy="110" r="2" fill="inherit" />
              <circle cx="46" cy="114" r="2" fill="inherit" />
              <circle cx="50" cy="114" r="2" fill="inherit" />
              <circle cx="74" cy="114" r="2" fill="inherit" />
              <circle cx="78" cy="114" r="2" fill="inherit" />
              <circle cx="82" cy="114" r="2" fill="inherit" />
              <circle cx="86" cy="114" r="2" fill="inherit" />
              <circle cx="46" cy="118" r="2" fill="inherit" />
              <circle cx="50" cy="118" r="2" fill="inherit" />
              <circle cx="54" cy="118" r="2" fill="inherit" />
              <circle cx="58" cy="118" r="2" fill="inherit" />
              <circle cx="70" cy="118" r="2" fill="inherit" />
              <circle cx="74" cy="118" r="2" fill="inherit" />
              <circle cx="78" cy="118" r="2" fill="inherit" />
              <circle cx="54" cy="122" r="2" fill="inherit" />
              <circle cx="58" cy="122" r="2" fill="inherit" />
              <circle cx="62" cy="122" r="2" fill="inherit" />
              <circle cx="66" cy="122" r="2" fill="inherit" />
              <circle cx="70" cy="122" r="2" fill="inherit" />
              <circle cx="74" cy="122" r="2" fill="inherit" />
              <circle cx="62" cy="126" r="2" fill="inherit" />
              <circle cx="66" cy="126" r="2" fill="inherit" />
    </svg>
  );
};

export default NodeJs;
