import React from "react";

interface Prop {
    style?: React.CSSProperties;
    className?: string;
}

const NextJs: React.FC<Prop> = ({ style, className }) => {
  return (
    <svg
      className={className}
      viewBox="0 0 130 130"
      xmlns="http://www.w3.org/2000/svg"
      style={style}
    >
      <circle cx="46" cy="2" r="2" fill="inherit" />
              <circle cx="50" cy="2" r="2" fill="inherit" />
              <circle cx="54" cy="2" r="2" fill="inherit" />
              <circle cx="58" cy="2" r="2" fill="inherit" />
              <circle cx="62" cy="2" r="2" fill="inherit" />
              <circle cx="66" cy="2" r="2" fill="inherit" />
              <circle cx="70" cy="2" r="2" fill="inherit" />
              <circle cx="74" cy="2" r="2" fill="inherit" />
              <circle cx="78" cy="2" r="2" fill="inherit" />
              <circle cx="38" cy="6" r="2" fill="inherit" />
              <circle cx="42" cy="6" r="2" fill="inherit" />
              <circle cx="46" cy="6" r="2" fill="inherit" />
              <circle cx="50" cy="6" r="2" fill="inherit" />
              <circle cx="54" cy="6" r="2" fill="inherit" />
              <circle cx="58" cy="6" r="2" fill="inherit" />
              <circle cx="62" cy="6" r="2" fill="inherit" />
              <circle cx="66" cy="6" r="2" fill="inherit" />
              <circle cx="70" cy="6" r="2" fill="inherit" />
              <circle cx="74" cy="6" r="2" fill="inherit" />
              <circle cx="78" cy="6" r="2" fill="inherit" />
              <circle cx="82" cy="6" r="2" fill="inherit" />
              <circle cx="86" cy="6" r="2" fill="inherit" />
              <circle cx="34" cy="10" r="2" fill="inherit" />
              <circle cx="38" cy="10" r="2" fill="inherit" />
              <circle cx="42" cy="10" r="2" fill="inherit" />
              <circle cx="50" cy="10" r="2" fill="inherit" />
              <circle cx="54" cy="10" r="2" fill="inherit" />
              <circle cx="58" cy="10" r="2" fill="inherit" />
              <circle cx="62" cy="10" r="2" fill="inherit" />
              <circle cx="66" cy="10" r="2" fill="inherit" />
              <circle cx="70" cy="10" r="2" fill="inherit" />
              <circle cx="74" cy="10" r="2" fill="inherit" />
              <circle cx="78" cy="10" r="2" fill="inherit" />
              <circle cx="82" cy="10" r="2" fill="inherit" />
              <circle cx="86" cy="10" r="2" fill="inherit" />
              <circle cx="90" cy="10" r="2" fill="inherit" />
              <circle cx="34" cy="14" r="2" fill="inherit" />
              <circle cx="38" cy="14" r="2" fill="inherit" />
              <circle cx="54" cy="14" r="2" fill="inherit" />
              <circle cx="58" cy="14" r="2" fill="inherit" />
              <circle cx="62" cy="14" r="2" fill="inherit" />
              <circle cx="66" cy="14" r="2" fill="inherit" />
              <circle cx="70" cy="14" r="2" fill="inherit" />
              <circle cx="74" cy="14" r="2" fill="inherit" />
              <circle cx="78" cy="14" r="2" fill="inherit" />
              <circle cx="82" cy="14" r="2" fill="inherit" />
              <circle cx="86" cy="14" r="2" fill="inherit" />
              <circle cx="90" cy="14" r="2" fill="inherit" />
              <circle cx="34" cy="18" r="2" fill="inherit" />
              <circle cx="38" cy="18" r="2" fill="inherit" />
              <circle cx="54" cy="18" r="2" fill="inherit" />
              <circle cx="58" cy="18" r="2" fill="inherit" />
              <circle cx="62" cy="18" r="2" fill="inherit" />
              <circle cx="66" cy="18" r="2" fill="inherit" />
              <circle cx="70" cy="18" r="2" fill="inherit" />
              <circle cx="74" cy="18" r="2" fill="inherit" />
              <circle cx="78" cy="18" r="2" fill="inherit" />
              <circle cx="82" cy="18" r="2" fill="inherit" />
              <circle cx="86" cy="18" r="2" fill="inherit" />
              <circle cx="90" cy="18" r="2" fill="inherit" />
              <circle cx="94" cy="18" r="2" fill="inherit" />
              <circle cx="34" cy="22" r="2" fill="inherit" />
              <circle cx="38" cy="22" r="2" fill="inherit" />
              <circle cx="42" cy="22" r="2" fill="inherit" />
              <circle cx="46" cy="22" r="2" fill="inherit" />
              <circle cx="50" cy="22" r="2" fill="inherit" />
              <circle cx="54" cy="22" r="2" fill="inherit" />
              <circle cx="58" cy="22" r="2" fill="inherit" />
              <circle cx="62" cy="22" r="2" fill="inherit" />
              <circle cx="66" cy="22" r="2" fill="inherit" />
              <circle cx="70" cy="22" r="2" fill="inherit" />
              <circle cx="74" cy="22" r="2" fill="inherit" />
              <circle cx="78" cy="22" r="2" fill="inherit" />
              <circle cx="82" cy="22" r="2" fill="inherit" />
              <circle cx="86" cy="22" r="2" fill="inherit" />
              <circle cx="90" cy="22" r="2" fill="inherit" />
              <circle cx="94" cy="22" r="2" fill="inherit" />
              <circle cx="34" cy="26" r="2" fill="inherit" />
              <circle cx="38" cy="26" r="2" fill="inherit" />
              <circle cx="42" cy="26" r="2" fill="inherit" />
              <circle cx="46" cy="26" r="2" fill="inherit" />
              <circle cx="50" cy="26" r="2" fill="inherit" />
              <circle cx="54" cy="26" r="2" fill="inherit" />
              <circle cx="58" cy="26" r="2" fill="inherit" />
              <circle cx="62" cy="26" r="2" fill="inherit" />
              <circle cx="66" cy="26" r="2" fill="inherit" />
              <circle cx="70" cy="26" r="2" fill="inherit" />
              <circle cx="74" cy="26" r="2" fill="inherit" />
              <circle cx="78" cy="26" r="2" fill="inherit" />
              <circle cx="82" cy="26" r="2" fill="inherit" />
              <circle cx="86" cy="26" r="2" fill="inherit" />
              <circle cx="90" cy="26" r="2" fill="inherit" />
              <circle cx="94" cy="26" r="2" fill="inherit" />
              <circle cx="66" cy="30" r="2" fill="inherit" />
              <circle cx="70" cy="30" r="2" fill="inherit" />
              <circle cx="74" cy="30" r="2" fill="inherit" />
              <circle cx="78" cy="30" r="2" fill="inherit" />
              <circle cx="82" cy="30" r="2" fill="inherit" />
              <circle cx="86" cy="30" r="2" fill="inherit" />
              <circle cx="90" cy="30" r="2" fill="inherit" />
              <circle cx="94" cy="30" r="2" fill="inherit" />
              <circle cx="18" cy="34" r="2" fill="inherit" />
              <circle cx="22" cy="34" r="2" fill="inherit" />
              <circle cx="26" cy="34" r="2" fill="inherit" />
              <circle cx="30" cy="34" r="2" fill="inherit" />
              <circle cx="34" cy="34" r="2" fill="inherit" />
              <circle cx="38" cy="34" r="2" fill="inherit" />
              <circle cx="42" cy="34" r="2" fill="inherit" />
              <circle cx="46" cy="34" r="2" fill="inherit" />
              <circle cx="50" cy="34" r="2" fill="inherit" />
              <circle cx="54" cy="34" r="2" fill="inherit" />
              <circle cx="58" cy="34" r="2" fill="inherit" />
              <circle cx="62" cy="34" r="2" fill="inherit" />
              <circle cx="66" cy="34" r="2" fill="inherit" />
              <circle cx="70" cy="34" r="2" fill="inherit" />
              <circle cx="74" cy="34" r="2" fill="inherit" />
              <circle cx="78" cy="34" r="2" fill="inherit" />
              <circle cx="82" cy="34" r="2" fill="inherit" />
              <circle cx="86" cy="34" r="2" fill="inherit" />
              <circle cx="90" cy="34" r="2" fill="inherit" />
              <circle cx="94" cy="34" r="2" fill="inherit" />
              <circle cx="102" cy="34" r="2" fill="inherit" />
              <circle cx="106" cy="34" r="2" fill="inherit" />
              <circle cx="110" cy="34" r="2" fill="inherit" />
              <circle cx="114" cy="34" r="2" fill="inherit" />
              <circle cx="10" cy="38" r="2" fill="inherit" />
              <circle cx="14" cy="38" r="2" fill="inherit" />
              <circle cx="18" cy="38" r="2" fill="inherit" />
              <circle cx="22" cy="38" r="2" fill="inherit" />
              <circle cx="26" cy="38" r="2" fill="inherit" />
              <circle cx="30" cy="38" r="2" fill="inherit" />
              <circle cx="34" cy="38" r="2" fill="inherit" />
              <circle cx="38" cy="38" r="2" fill="inherit" />
              <circle cx="42" cy="38" r="2" fill="inherit" />
              <circle cx="46" cy="38" r="2" fill="inherit" />
              <circle cx="50" cy="38" r="2" fill="inherit" />
              <circle cx="54" cy="38" r="2" fill="inherit" />
              <circle cx="58" cy="38" r="2" fill="inherit" />
              <circle cx="62" cy="38" r="2" fill="inherit" />
              <circle cx="66" cy="38" r="2" fill="inherit" />
              <circle cx="70" cy="38" r="2" fill="inherit" />
              <circle cx="74" cy="38" r="2" fill="inherit" />
              <circle cx="78" cy="38" r="2" fill="inherit" />
              <circle cx="82" cy="38" r="2" fill="inherit" />
              <circle cx="86" cy="38" r="2" fill="inherit" />
              <circle cx="90" cy="38" r="2" fill="inherit" />
              <circle cx="94" cy="38" r="2" fill="inherit" />
              <circle cx="102" cy="38" r="2" fill="inherit" />
              <circle cx="106" cy="38" r="2" fill="inherit" />
              <circle cx="110" cy="38" r="2" fill="inherit" />
              <circle cx="114" cy="38" r="2" fill="inherit" />
              <circle cx="118" cy="38" r="2" fill="inherit" />
              <circle cx="6" cy="42" r="2" fill="inherit" />
              <circle cx="10" cy="42" r="2" fill="inherit" />
              <circle cx="14" cy="42" r="2" fill="inherit" />
              <circle cx="18" cy="42" r="2" fill="inherit" />
              <circle cx="22" cy="42" r="2" fill="inherit" />
              <circle cx="26" cy="42" r="2" fill="inherit" />
              <circle cx="30" cy="42" r="2" fill="inherit" />
              <circle cx="34" cy="42" r="2" fill="inherit" />
              <circle cx="38" cy="42" r="2" fill="inherit" />
              <circle cx="42" cy="42" r="2" fill="inherit" />
              <circle cx="46" cy="42" r="2" fill="inherit" />
              <circle cx="50" cy="42" r="2" fill="inherit" />
              <circle cx="54" cy="42" r="2" fill="inherit" />
              <circle cx="58" cy="42" r="2" fill="inherit" />
              <circle cx="62" cy="42" r="2" fill="inherit" />
              <circle cx="66" cy="42" r="2" fill="inherit" />
              <circle cx="70" cy="42" r="2" fill="inherit" />
              <circle cx="74" cy="42" r="2" fill="inherit" />
              <circle cx="78" cy="42" r="2" fill="inherit" />
              <circle cx="82" cy="42" r="2" fill="inherit" />
              <circle cx="86" cy="42" r="2" fill="inherit" />
              <circle cx="90" cy="42" r="2" fill="inherit" />
              <circle cx="94" cy="42" r="2" fill="inherit" />
              <circle cx="102" cy="42" r="2" fill="inherit" />
              <circle cx="106" cy="42" r="2" fill="inherit" />
              <circle cx="110" cy="42" r="2" fill="inherit" />
              <circle cx="114" cy="42" r="2" fill="inherit" />
              <circle cx="118" cy="42" r="2" fill="inherit" />
              <circle cx="122" cy="42" r="2" fill="inherit" />
              <circle cx="6" cy="46" r="2" fill="inherit" />
              <circle cx="10" cy="46" r="2" fill="inherit" />
              <circle cx="14" cy="46" r="2" fill="inherit" />
              <circle cx="18" cy="46" r="2" fill="inherit" />
              <circle cx="22" cy="46" r="2" fill="inherit" />
              <circle cx="26" cy="46" r="2" fill="inherit" />
              <circle cx="30" cy="46" r="2" fill="inherit" />
              <circle cx="34" cy="46" r="2" fill="inherit" />
              <circle cx="38" cy="46" r="2" fill="inherit" />
              <circle cx="42" cy="46" r="2" fill="inherit" />
              <circle cx="46" cy="46" r="2" fill="inherit" />
              <circle cx="50" cy="46" r="2" fill="inherit" />
              <circle cx="54" cy="46" r="2" fill="inherit" />
              <circle cx="58" cy="46" r="2" fill="inherit" />
              <circle cx="62" cy="46" r="2" fill="inherit" />
              <circle cx="66" cy="46" r="2" fill="inherit" />
              <circle cx="70" cy="46" r="2" fill="inherit" />
              <circle cx="74" cy="46" r="2" fill="inherit" />
              <circle cx="78" cy="46" r="2" fill="inherit" />
              <circle cx="82" cy="46" r="2" fill="inherit" />
              <circle cx="86" cy="46" r="2" fill="inherit" />
              <circle cx="90" cy="46" r="2" fill="inherit" />
              <circle cx="94" cy="46" r="2" fill="inherit" />
              <circle cx="102" cy="46" r="2" fill="inherit" />
              <circle cx="106" cy="46" r="2" fill="inherit" />
              <circle cx="110" cy="46" r="2" fill="inherit" />
              <circle cx="114" cy="46" r="2" fill="inherit" />
              <circle cx="118" cy="46" r="2" fill="inherit" />
              <circle cx="122" cy="46" r="2" fill="inherit" />
              <circle cx="2" cy="50" r="2" fill="inherit" />
              <circle cx="6" cy="50" r="2" fill="inherit" />
              <circle cx="10" cy="50" r="2" fill="inherit" />
              <circle cx="14" cy="50" r="2" fill="inherit" />
              <circle cx="18" cy="50" r="2" fill="inherit" />
              <circle cx="22" cy="50" r="2" fill="inherit" />
              <circle cx="26" cy="50" r="2" fill="inherit" />
              <circle cx="30" cy="50" r="2" fill="inherit" />
              <circle cx="34" cy="50" r="2" fill="inherit" />
              <circle cx="38" cy="50" r="2" fill="inherit" />
              <circle cx="42" cy="50" r="2" fill="inherit" />
              <circle cx="46" cy="50" r="2" fill="inherit" />
              <circle cx="50" cy="50" r="2" fill="inherit" />
              <circle cx="54" cy="50" r="2" fill="inherit" />
              <circle cx="58" cy="50" r="2" fill="inherit" />
              <circle cx="62" cy="50" r="2" fill="inherit" />
              <circle cx="66" cy="50" r="2" fill="inherit" />
              <circle cx="70" cy="50" r="2" fill="inherit" />
              <circle cx="74" cy="50" r="2" fill="inherit" />
              <circle cx="78" cy="50" r="2" fill="inherit" />
              <circle cx="82" cy="50" r="2" fill="inherit" />
              <circle cx="86" cy="50" r="2" fill="inherit" />
              <circle cx="90" cy="50" r="2" fill="inherit" />
              <circle cx="102" cy="50" r="2" fill="inherit" />
              <circle cx="106" cy="50" r="2" fill="inherit" />
              <circle cx="110" cy="50" r="2" fill="inherit" />
              <circle cx="114" cy="50" r="2" fill="inherit" />
              <circle cx="118" cy="50" r="2" fill="inherit" />
              <circle cx="122" cy="50" r="2" fill="inherit" />
              <circle cx="126" cy="50" r="2" fill="inherit" />
              <circle cx="2" cy="54" r="2" fill="inherit" />
              <circle cx="6" cy="54" r="2" fill="inherit" />
              <circle cx="10" cy="54" r="2" fill="inherit" />
              <circle cx="14" cy="54" r="2" fill="inherit" />
              <circle cx="18" cy="54" r="2" fill="inherit" />
              <circle cx="22" cy="54" r="2" fill="inherit" />
              <circle cx="26" cy="54" r="2" fill="inherit" />
              <circle cx="30" cy="54" r="2" fill="inherit" />
              <circle cx="34" cy="54" r="2" fill="inherit" />
              <circle cx="38" cy="54" r="2" fill="inherit" />
              <circle cx="42" cy="54" r="2" fill="inherit" />
              <circle cx="46" cy="54" r="2" fill="inherit" />
              <circle cx="50" cy="54" r="2" fill="inherit" />
              <circle cx="54" cy="54" r="2" fill="inherit" />
              <circle cx="58" cy="54" r="2" fill="inherit" />
              <circle cx="62" cy="54" r="2" fill="inherit" />
              <circle cx="66" cy="54" r="2" fill="inherit" />
              <circle cx="70" cy="54" r="2" fill="inherit" />
              <circle cx="74" cy="54" r="2" fill="inherit" />
              <circle cx="78" cy="54" r="2" fill="inherit" />
              <circle cx="82" cy="54" r="2" fill="inherit" />
              <circle cx="86" cy="54" r="2" fill="inherit" />
              <circle cx="90" cy="54" r="2" fill="inherit" />
              <circle cx="98" cy="54" r="2" fill="inherit" />
              <circle cx="102" cy="54" r="2" fill="inherit" />
              <circle cx="106" cy="54" r="2" fill="inherit" />
              <circle cx="110" cy="54" r="2" fill="inherit" />
              <circle cx="114" cy="54" r="2" fill="inherit" />
              <circle cx="118" cy="54" r="2" fill="inherit" />
              <circle cx="122" cy="54" r="2" fill="inherit" />
              <circle cx="126" cy="54" r="2" fill="inherit" />
              <circle cx="2" cy="58" r="2" fill="inherit" />
              <circle cx="6" cy="58" r="2" fill="inherit" />
              <circle cx="10" cy="58" r="2" fill="inherit" />
              <circle cx="14" cy="58" r="2" fill="inherit" />
              <circle cx="18" cy="58" r="2" fill="inherit" />
              <circle cx="22" cy="58" r="2" fill="inherit" />
              <circle cx="26" cy="58" r="2" fill="inherit" />
              <circle cx="30" cy="58" r="2" fill="inherit" />
              <circle cx="34" cy="58" r="2" fill="inherit" />
              <circle cx="38" cy="58" r="2" fill="inherit" />
              <circle cx="42" cy="58" r="2" fill="inherit" />
              <circle cx="46" cy="58" r="2" fill="inherit" />
              <circle cx="50" cy="58" r="2" fill="inherit" />
              <circle cx="54" cy="58" r="2" fill="inherit" />
              <circle cx="58" cy="58" r="2" fill="inherit" />
              <circle cx="62" cy="58" r="2" fill="inherit" />
              <circle cx="66" cy="58" r="2" fill="inherit" />
              <circle cx="70" cy="58" r="2" fill="inherit" />
              <circle cx="74" cy="58" r="2" fill="inherit" />
              <circle cx="78" cy="58" r="2" fill="inherit" />
              <circle cx="82" cy="58" r="2" fill="inherit" />
              <circle cx="86" cy="58" r="2" fill="inherit" />
              <circle cx="98" cy="58" r="2" fill="inherit" />
              <circle cx="102" cy="58" r="2" fill="inherit" />
              <circle cx="106" cy="58" r="2" fill="inherit" />
              <circle cx="110" cy="58" r="2" fill="inherit" />
              <circle cx="114" cy="58" r="2" fill="inherit" />
              <circle cx="118" cy="58" r="2" fill="inherit" />
              <circle cx="122" cy="58" r="2" fill="inherit" />
              <circle cx="126" cy="58" r="2" fill="inherit" />
              <circle cx="2" cy="62" r="2" fill="inherit" />
              <circle cx="6" cy="62" r="2" fill="inherit" />
              <circle cx="10" cy="62" r="2" fill="inherit" />
              <circle cx="14" cy="62" r="2" fill="inherit" />
              <circle cx="18" cy="62" r="2" fill="inherit" />
              <circle cx="22" cy="62" r="2" fill="inherit" />
              <circle cx="26" cy="62" r="2" fill="inherit" />
              <circle cx="30" cy="62" r="2" fill="inherit" />
              <circle cx="34" cy="62" r="2" fill="inherit" />
              <circle cx="38" cy="62" r="2" fill="inherit" />
              <circle cx="94" cy="62" r="2" fill="inherit" />
              <circle cx="98" cy="62" r="2" fill="inherit" />
              <circle cx="102" cy="62" r="2" fill="inherit" />
              <circle cx="106" cy="62" r="2" fill="inherit" />
              <circle cx="110" cy="62" r="2" fill="inherit" />
              <circle cx="114" cy="62" r="2" fill="inherit" />
              <circle cx="118" cy="62" r="2" fill="inherit" />
              <circle cx="122" cy="62" r="2" fill="inherit" />
              <circle cx="126" cy="62" r="2" fill="inherit" />
              <circle cx="2" cy="66" r="2" fill="inherit" />
              <circle cx="6" cy="66" r="2" fill="inherit" />
              <circle cx="10" cy="66" r="2" fill="inherit" />
              <circle cx="14" cy="66" r="2" fill="inherit" />
              <circle cx="18" cy="66" r="2" fill="inherit" />
              <circle cx="22" cy="66" r="2" fill="inherit" />
              <circle cx="26" cy="66" r="2" fill="inherit" />
              <circle cx="30" cy="66" r="2" fill="inherit" />
              <circle cx="50" cy="66" r="2" fill="inherit" />
              <circle cx="54" cy="66" r="2" fill="inherit" />
              <circle cx="58" cy="66" r="2" fill="inherit" />
              <circle cx="62" cy="66" r="2" fill="inherit" />
              <circle cx="66" cy="66" r="2" fill="inherit" />
              <circle cx="70" cy="66" r="2" fill="inherit" />
              <circle cx="74" cy="66" r="2" fill="inherit" />
              <circle cx="78" cy="66" r="2" fill="inherit" />
              <circle cx="82" cy="66" r="2" fill="inherit" />
              <circle cx="86" cy="66" r="2" fill="inherit" />
              <circle cx="90" cy="66" r="2" fill="inherit" />
              <circle cx="94" cy="66" r="2" fill="inherit" />
              <circle cx="98" cy="66" r="2" fill="inherit" />
              <circle cx="102" cy="66" r="2" fill="inherit" />
              <circle cx="106" cy="66" r="2" fill="inherit" />
              <circle cx="110" cy="66" r="2" fill="inherit" />
              <circle cx="114" cy="66" r="2" fill="inherit" />
              <circle cx="118" cy="66" r="2" fill="inherit" />
              <circle cx="122" cy="66" r="2" fill="inherit" />
              <circle cx="126" cy="66" r="2" fill="inherit" />
              <circle cx="2" cy="70" r="2" fill="inherit" />
              <circle cx="6" cy="70" r="2" fill="inherit" />
              <circle cx="10" cy="70" r="2" fill="inherit" />
              <circle cx="14" cy="70" r="2" fill="inherit" />
              <circle cx="18" cy="70" r="2" fill="inherit" />
              <circle cx="22" cy="70" r="2" fill="inherit" />
              <circle cx="26" cy="70" r="2" fill="inherit" />
              <circle cx="30" cy="70" r="2" fill="inherit" />
              <circle cx="38" cy="70" r="2" fill="inherit" />
              <circle cx="42" cy="70" r="2" fill="inherit" />
              <circle cx="46" cy="70" r="2" fill="inherit" />
              <circle cx="50" cy="70" r="2" fill="inherit" />
              <circle cx="54" cy="70" r="2" fill="inherit" />
              <circle cx="58" cy="70" r="2" fill="inherit" />
              <circle cx="62" cy="70" r="2" fill="inherit" />
              <circle cx="66" cy="70" r="2" fill="inherit" />
              <circle cx="70" cy="70" r="2" fill="inherit" />
              <circle cx="74" cy="70" r="2" fill="inherit" />
              <circle cx="78" cy="70" r="2" fill="inherit" />
              <circle cx="82" cy="70" r="2" fill="inherit" />
              <circle cx="86" cy="70" r="2" fill="inherit" />
              <circle cx="90" cy="70" r="2" fill="inherit" />
              <circle cx="94" cy="70" r="2" fill="inherit" />
              <circle cx="98" cy="70" r="2" fill="inherit" />
              <circle cx="102" cy="70" r="2" fill="inherit" />
              <circle cx="106" cy="70" r="2" fill="inherit" />
              <circle cx="110" cy="70" r="2" fill="inherit" />
              <circle cx="114" cy="70" r="2" fill="inherit" />
              <circle cx="118" cy="70" r="2" fill="inherit" />
              <circle cx="122" cy="70" r="2" fill="inherit" />
              <circle cx="126" cy="70" r="2" fill="inherit" />
              <circle cx="2" cy="74" r="2" fill="inherit" />
              <circle cx="6" cy="74" r="2" fill="inherit" />
              <circle cx="10" cy="74" r="2" fill="inherit" />
              <circle cx="14" cy="74" r="2" fill="inherit" />
              <circle cx="18" cy="74" r="2" fill="inherit" />
              <circle cx="22" cy="74" r="2" fill="inherit" />
              <circle cx="26" cy="74" r="2" fill="inherit" />
              <circle cx="38" cy="74" r="2" fill="inherit" />
              <circle cx="42" cy="74" r="2" fill="inherit" />
              <circle cx="46" cy="74" r="2" fill="inherit" />
              <circle cx="50" cy="74" r="2" fill="inherit" />
              <circle cx="54" cy="74" r="2" fill="inherit" />
              <circle cx="58" cy="74" r="2" fill="inherit" />
              <circle cx="62" cy="74" r="2" fill="inherit" />
              <circle cx="66" cy="74" r="2" fill="inherit" />
              <circle cx="70" cy="74" r="2" fill="inherit" />
              <circle cx="74" cy="74" r="2" fill="inherit" />
              <circle cx="78" cy="74" r="2" fill="inherit" />
              <circle cx="82" cy="74" r="2" fill="inherit" />
              <circle cx="86" cy="74" r="2" fill="inherit" />
              <circle cx="90" cy="74" r="2" fill="inherit" />
              <circle cx="94" cy="74" r="2" fill="inherit" />
              <circle cx="98" cy="74" r="2" fill="inherit" />
              <circle cx="102" cy="74" r="2" fill="inherit" />
              <circle cx="106" cy="74" r="2" fill="inherit" />
              <circle cx="110" cy="74" r="2" fill="inherit" />
              <circle cx="114" cy="74" r="2" fill="inherit" />
              <circle cx="118" cy="74" r="2" fill="inherit" />
              <circle cx="122" cy="74" r="2" fill="inherit" />
              <circle cx="126" cy="74" r="2" fill="inherit" />
              <circle cx="2" cy="78" r="2" fill="inherit" />
              <circle cx="6" cy="78" r="2" fill="inherit" />
              <circle cx="10" cy="78" r="2" fill="inherit" />
              <circle cx="14" cy="78" r="2" fill="inherit" />
              <circle cx="18" cy="78" r="2" fill="inherit" />
              <circle cx="22" cy="78" r="2" fill="inherit" />
              <circle cx="26" cy="78" r="2" fill="inherit" />
              <circle cx="34" cy="78" r="2" fill="inherit" />
              <circle cx="38" cy="78" r="2" fill="inherit" />
              <circle cx="42" cy="78" r="2" fill="inherit" />
              <circle cx="46" cy="78" r="2" fill="inherit" />
              <circle cx="50" cy="78" r="2" fill="inherit" />
              <circle cx="54" cy="78" r="2" fill="inherit" />
              <circle cx="58" cy="78" r="2" fill="inherit" />
              <circle cx="62" cy="78" r="2" fill="inherit" />
              <circle cx="66" cy="78" r="2" fill="inherit" />
              <circle cx="70" cy="78" r="2" fill="inherit" />
              <circle cx="74" cy="78" r="2" fill="inherit" />
              <circle cx="78" cy="78" r="2" fill="inherit" />
              <circle cx="82" cy="78" r="2" fill="inherit" />
              <circle cx="86" cy="78" r="2" fill="inherit" />
              <circle cx="90" cy="78" r="2" fill="inherit" />
              <circle cx="94" cy="78" r="2" fill="inherit" />
              <circle cx="98" cy="78" r="2" fill="inherit" />
              <circle cx="102" cy="78" r="2" fill="inherit" />
              <circle cx="106" cy="78" r="2" fill="inherit" />
              <circle cx="110" cy="78" r="2" fill="inherit" />
              <circle cx="114" cy="78" r="2" fill="inherit" />
              <circle cx="118" cy="78" r="2" fill="inherit" />
              <circle cx="122" cy="78" r="2" fill="inherit" />
              <circle cx="6" cy="82" r="2" fill="inherit" />
              <circle cx="10" cy="82" r="2" fill="inherit" />
              <circle cx="14" cy="82" r="2" fill="inherit" />
              <circle cx="18" cy="82" r="2" fill="inherit" />
              <circle cx="22" cy="82" r="2" fill="inherit" />
              <circle cx="26" cy="82" r="2" fill="inherit" />
              <circle cx="34" cy="82" r="2" fill="inherit" />
              <circle cx="38" cy="82" r="2" fill="inherit" />
              <circle cx="42" cy="82" r="2" fill="inherit" />
              <circle cx="46" cy="82" r="2" fill="inherit" />
              <circle cx="50" cy="82" r="2" fill="inherit" />
              <circle cx="54" cy="82" r="2" fill="inherit" />
              <circle cx="58" cy="82" r="2" fill="inherit" />
              <circle cx="62" cy="82" r="2" fill="inherit" />
              <circle cx="66" cy="82" r="2" fill="inherit" />
              <circle cx="70" cy="82" r="2" fill="inherit" />
              <circle cx="74" cy="82" r="2" fill="inherit" />
              <circle cx="78" cy="82" r="2" fill="inherit" />
              <circle cx="82" cy="82" r="2" fill="inherit" />
              <circle cx="86" cy="82" r="2" fill="inherit" />
              <circle cx="90" cy="82" r="2" fill="inherit" />
              <circle cx="94" cy="82" r="2" fill="inherit" />
              <circle cx="98" cy="82" r="2" fill="inherit" />
              <circle cx="102" cy="82" r="2" fill="inherit" />
              <circle cx="106" cy="82" r="2" fill="inherit" />
              <circle cx="110" cy="82" r="2" fill="inherit" />
              <circle cx="114" cy="82" r="2" fill="inherit" />
              <circle cx="118" cy="82" r="2" fill="inherit" />
              <circle cx="122" cy="82" r="2" fill="inherit" />
              <circle cx="6" cy="86" r="2" fill="inherit" />
              <circle cx="10" cy="86" r="2" fill="inherit" />
              <circle cx="14" cy="86" r="2" fill="inherit" />
              <circle cx="18" cy="86" r="2" fill="inherit" />
              <circle cx="22" cy="86" r="2" fill="inherit" />
              <circle cx="26" cy="86" r="2" fill="inherit" />
              <circle cx="34" cy="86" r="2" fill="inherit" />
              <circle cx="38" cy="86" r="2" fill="inherit" />
              <circle cx="42" cy="86" r="2" fill="inherit" />
              <circle cx="46" cy="86" r="2" fill="inherit" />
              <circle cx="50" cy="86" r="2" fill="inherit" />
              <circle cx="54" cy="86" r="2" fill="inherit" />
              <circle cx="58" cy="86" r="2" fill="inherit" />
              <circle cx="62" cy="86" r="2" fill="inherit" />
              <circle cx="66" cy="86" r="2" fill="inherit" />
              <circle cx="70" cy="86" r="2" fill="inherit" />
              <circle cx="74" cy="86" r="2" fill="inherit" />
              <circle cx="78" cy="86" r="2" fill="inherit" />
              <circle cx="82" cy="86" r="2" fill="inherit" />
              <circle cx="86" cy="86" r="2" fill="inherit" />
              <circle cx="90" cy="86" r="2" fill="inherit" />
              <circle cx="94" cy="86" r="2" fill="inherit" />
              <circle cx="98" cy="86" r="2" fill="inherit" />
              <circle cx="102" cy="86" r="2" fill="inherit" />
              <circle cx="106" cy="86" r="2" fill="inherit" />
              <circle cx="110" cy="86" r="2" fill="inherit" />
              <circle cx="114" cy="86" r="2" fill="inherit" />
              <circle cx="118" cy="86" r="2" fill="inherit" />
              <circle cx="122" cy="86" r="2" fill="inherit" />
              <circle cx="10" cy="90" r="2" fill="inherit" />
              <circle cx="14" cy="90" r="2" fill="inherit" />
              <circle cx="18" cy="90" r="2" fill="inherit" />
              <circle cx="22" cy="90" r="2" fill="inherit" />
              <circle cx="26" cy="90" r="2" fill="inherit" />
              <circle cx="34" cy="90" r="2" fill="inherit" />
              <circle cx="38" cy="90" r="2" fill="inherit" />
              <circle cx="42" cy="90" r="2" fill="inherit" />
              <circle cx="46" cy="90" r="2" fill="inherit" />
              <circle cx="50" cy="90" r="2" fill="inherit" />
              <circle cx="54" cy="90" r="2" fill="inherit" />
              <circle cx="58" cy="90" r="2" fill="inherit" />
              <circle cx="62" cy="90" r="2" fill="inherit" />
              <circle cx="66" cy="90" r="2" fill="inherit" />
              <circle cx="70" cy="90" r="2" fill="inherit" />
              <circle cx="74" cy="90" r="2" fill="inherit" />
              <circle cx="78" cy="90" r="2" fill="inherit" />
              <circle cx="82" cy="90" r="2" fill="inherit" />
              <circle cx="86" cy="90" r="2" fill="inherit" />
              <circle cx="90" cy="90" r="2" fill="inherit" />
              <circle cx="94" cy="90" r="2" fill="inherit" />
              <circle cx="98" cy="90" r="2" fill="inherit" />
              <circle cx="102" cy="90" r="2" fill="inherit" />
              <circle cx="106" cy="90" r="2" fill="inherit" />
              <circle cx="110" cy="90" r="2" fill="inherit" />
              <circle cx="114" cy="90" r="2" fill="inherit" />
              <circle cx="118" cy="90" r="2" fill="inherit" />
              <circle cx="14" cy="94" r="2" fill="inherit" />
              <circle cx="18" cy="94" r="2" fill="inherit" />
              <circle cx="22" cy="94" r="2" fill="inherit" />
              <circle cx="26" cy="94" r="2" fill="inherit" />
              <circle cx="34" cy="94" r="2" fill="inherit" />
              <circle cx="38" cy="94" r="2" fill="inherit" />
              <circle cx="42" cy="94" r="2" fill="inherit" />
              <circle cx="46" cy="94" r="2" fill="inherit" />
              <circle cx="50" cy="94" r="2" fill="inherit" />
              <circle cx="54" cy="94" r="2" fill="inherit" />
              <circle cx="58" cy="94" r="2" fill="inherit" />
              <circle cx="62" cy="94" r="2" fill="inherit" />
              <circle cx="34" cy="98" r="2" fill="inherit" />
              <circle cx="38" cy="98" r="2" fill="inherit" />
              <circle cx="42" cy="98" r="2" fill="inherit" />
              <circle cx="46" cy="98" r="2" fill="inherit" />
              <circle cx="50" cy="98" r="2" fill="inherit" />
              <circle cx="54" cy="98" r="2" fill="inherit" />
              <circle cx="58" cy="98" r="2" fill="inherit" />
              <circle cx="62" cy="98" r="2" fill="inherit" />
              <circle cx="34" cy="102" r="2" fill="inherit" />
              <circle cx="38" cy="102" r="2" fill="inherit" />
              <circle cx="42" cy="102" r="2" fill="inherit" />
              <circle cx="46" cy="102" r="2" fill="inherit" />
              <circle cx="50" cy="102" r="2" fill="inherit" />
              <circle cx="54" cy="102" r="2" fill="inherit" />
              <circle cx="58" cy="102" r="2" fill="inherit" />
              <circle cx="62" cy="102" r="2" fill="inherit" />
              <circle cx="66" cy="102" r="2" fill="inherit" />
              <circle cx="70" cy="102" r="2" fill="inherit" />
              <circle cx="74" cy="102" r="2" fill="inherit" />
              <circle cx="78" cy="102" r="2" fill="inherit" />
              <circle cx="82" cy="102" r="2" fill="inherit" />
              <circle cx="86" cy="102" r="2" fill="inherit" />
              <circle cx="90" cy="102" r="2" fill="inherit" />
              <circle cx="94" cy="102" r="2" fill="inherit" />
              <circle cx="34" cy="106" r="2" fill="inherit" />
              <circle cx="38" cy="106" r="2" fill="inherit" />
              <circle cx="42" cy="106" r="2" fill="inherit" />
              <circle cx="46" cy="106" r="2" fill="inherit" />
              <circle cx="50" cy="106" r="2" fill="inherit" />
              <circle cx="54" cy="106" r="2" fill="inherit" />
              <circle cx="58" cy="106" r="2" fill="inherit" />
              <circle cx="62" cy="106" r="2" fill="inherit" />
              <circle cx="66" cy="106" r="2" fill="inherit" />
              <circle cx="70" cy="106" r="2" fill="inherit" />
              <circle cx="74" cy="106" r="2" fill="inherit" />
              <circle cx="78" cy="106" r="2" fill="inherit" />
              <circle cx="82" cy="106" r="2" fill="inherit" />
              <circle cx="86" cy="106" r="2" fill="inherit" />
              <circle cx="90" cy="106" r="2" fill="inherit" />
              <circle cx="94" cy="106" r="2" fill="inherit" />
              <circle cx="34" cy="110" r="2" fill="inherit" />
              <circle cx="38" cy="110" r="2" fill="inherit" />
              <circle cx="42" cy="110" r="2" fill="inherit" />
              <circle cx="46" cy="110" r="2" fill="inherit" />
              <circle cx="50" cy="110" r="2" fill="inherit" />
              <circle cx="54" cy="110" r="2" fill="inherit" />
              <circle cx="58" cy="110" r="2" fill="inherit" />
              <circle cx="62" cy="110" r="2" fill="inherit" />
              <circle cx="66" cy="110" r="2" fill="inherit" />
              <circle cx="70" cy="110" r="2" fill="inherit" />
              <circle cx="74" cy="110" r="2" fill="inherit" />
              <circle cx="90" cy="110" r="2" fill="inherit" />
              <circle cx="94" cy="110" r="2" fill="inherit" />
              <circle cx="34" cy="114" r="2" fill="inherit" />
              <circle cx="38" cy="114" r="2" fill="inherit" />
              <circle cx="42" cy="114" r="2" fill="inherit" />
              <circle cx="46" cy="114" r="2" fill="inherit" />
              <circle cx="50" cy="114" r="2" fill="inherit" />
              <circle cx="54" cy="114" r="2" fill="inherit" />
              <circle cx="58" cy="114" r="2" fill="inherit" />
              <circle cx="62" cy="114" r="2" fill="inherit" />
              <circle cx="66" cy="114" r="2" fill="inherit" />
              <circle cx="70" cy="114" r="2" fill="inherit" />
              <circle cx="74" cy="114" r="2" fill="inherit" />
              <circle cx="90" cy="114" r="2" fill="inherit" />
              <circle cx="94" cy="114" r="2" fill="inherit" />
              <circle cx="38" cy="118" r="2" fill="inherit" />
              <circle cx="42" cy="118" r="2" fill="inherit" />
              <circle cx="46" cy="118" r="2" fill="inherit" />
              <circle cx="50" cy="118" r="2" fill="inherit" />
              <circle cx="54" cy="118" r="2" fill="inherit" />
              <circle cx="58" cy="118" r="2" fill="inherit" />
              <circle cx="62" cy="118" r="2" fill="inherit" />
              <circle cx="66" cy="118" r="2" fill="inherit" />
              <circle cx="70" cy="118" r="2" fill="inherit" />
              <circle cx="74" cy="118" r="2" fill="inherit" />
              <circle cx="78" cy="118" r="2" fill="inherit" />
              <circle cx="82" cy="118" r="2" fill="inherit" />
              <circle cx="86" cy="118" r="2" fill="inherit" />
              <circle cx="90" cy="118" r="2" fill="inherit" />
              <circle cx="42" cy="122" r="2" fill="inherit" />
              <circle cx="46" cy="122" r="2" fill="inherit" />
              <circle cx="50" cy="122" r="2" fill="inherit" />
              <circle cx="54" cy="122" r="2" fill="inherit" />
              <circle cx="58" cy="122" r="2" fill="inherit" />
              <circle cx="62" cy="122" r="2" fill="inherit" />
              <circle cx="66" cy="122" r="2" fill="inherit" />
              <circle cx="70" cy="122" r="2" fill="inherit" />
              <circle cx="74" cy="122" r="2" fill="inherit" />
              <circle cx="78" cy="122" r="2" fill="inherit" />
              <circle cx="82" cy="122" r="2" fill="inherit" />
              <circle cx="86" cy="122" r="2" fill="inherit" />
              <circle cx="90" cy="122" r="2" fill="inherit" />
              <circle cx="54" cy="126" r="2" fill="inherit" />
              <circle cx="58" cy="126" r="2" fill="inherit" />
              <circle cx="62" cy="126" r="2" fill="inherit" />
              <circle cx="66" cy="126" r="2" fill="inherit" />
              <circle cx="70" cy="126" r="2" fill="inherit" />
              <circle cx="74" cy="126" r="2" fill="inherit" />
              <circle cx="78" cy="126" r="2" fill="inherit" />
    </svg>
  );
};

export default NextJs;
